name: 'audit_helper'
version: '0.4.0'
config-version: 2

require-dbt-version: [">=1.2.0", "<2.0.0"]
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
flags:
  require_generic_test_arguments_property: true