name: 'snowflake_spend'
version: '1.0'
config-version: 2
require-dbt-version: ">=0.17.0"

analysis-paths: ["analysis"] # path with analysis files which are compiled, but not run
clean-targets: ["target"]  # directories removed by the clean task
test-paths: ["test"]       # where to store test results
flags:
  require_generic_test_arguments_property: true
seed-paths: ["data"]       # load CSVs from this directory with `dbt seed`
model-paths: ["models"]    # paths with source code to compile