name: 'dbt_utils'
version: '0.1.0'

require-dbt-version: [">=1.3.0", "<2.0.0"]

config-version: 2

clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
flags:
  require_generic_test_arguments_property: true